### ISSUE TITLE
always sign trust statements

### ISSUE THREAD

**Issue by dominictarr** [citizencode/trust-exchange#11]
having a trust statement without a signature on it is problematic because it would be easy for me to just make a bunch of them up - I understand that the reasoning is to be able to import trust statements from legacy systems like IMDB, which relys on centralization for security, instead of signatures.

Another option though, would be to have a bot that scrapes IMDB, and then signs those. This could be an official IMDB bot or something. You could run your own imdb scraper, to verify the official scraper and then sign a trust statement saying you verified the bot.

But without something like that, you'd _have_ to run the scraper you self, or just trust whoever gave you the data from IMDB.

**Comment by harlantwood** [comment]
Thanks @dominictarr, totally agree.

I wrote spike code around this, but haven't had a chance to implement it in the main codebase as yet.

Spike: https://github.com/citizencode/trust-exchange/blob/master/spike/sign.coffee

A PR around this would be awesome :smile:

**Comment by harlantwood** [comment]
We now sign the JSON-LD, Verifiable Claims style.
