### ISSUE TITLE
Move files & Merge spike/rails-weaviate

### ISSUE THREAD

**Issue by ocarissa** [citizencode/trust-exchange#38]
Opened this ticket in wrong repo. No delete function. Just a closed function. Created same ticket in vortex, where it should be.

**Comment by harlantwood** [comment]
Is this closed because we are tracking it elsewhere?  If so, ideal to put a link to the new ticket into the one you are closing.  @ocarissa

**Comment by ocarissa** [comment]
> Is this closed because we are tracking it elsewhere?  If so, ideal to put a link to the new ticket into the one you are closing.  @ocarissa 

It's closed because I accidentally created this issue in TrustGraph repo when it was supposed to be in Vortex. I couldn't find a proper "delete". So I closed it. I can add a link to the right one in the description, if that's what you mean.

**Comment by harlantwood** [comment]
Oh that’s fine then, just close with a note “created in wrong repo”. 

Yup there is no delete, only close.
